### ISSUE TITLE
Referring to wrong step before under Install & Set up

### ISSUE THREAD

**Issue by larsschellhas** [tmm/django-username-email#22]
In the text it says

> but with the following adjustments: After step 2, follow these instructions, but instead of using [...]. Then for **step 3** of the steps below, you should set AUTH_USER_MODEL to your custom user model instead of CUser’s CUser model

Since the "Step 3" part seems to be referring to Step 4 and step 3 really is to add the app to the installed apps, it seems as if you meant to say "step 4" here.

**Comment by ataylor32** [comment]
It's a little confusing since the steps numbers start at 0. When the README says "step 3", it means the step that is numbered 3, but it's actually the 4th step.

**Comment by larsschellhas** [comment]
Fair enough 😅

**Comment by ataylor32** [comment]
The README previously had its step numbers start at 0. When it was like that, GitHub rendered the step numbers starting at 0, but PyPI rendered the step numbers starting at 1, so it was inconsistent. I updated the README so that its step numbers start at 1 and now GitHub and PyPI both render the step numbers starting at 1.

**Comment by larsschellhas** [comment]
Perfect, thank you! 😊
